import { writeFileSync } from 'node:fs';

import { TestAggregatorClient } from './TestAggregatorClient.js';
import { NetworkId } from '../../src/api/NetworkId.js';
import { SigningService } from '../../src/crypto/secp256k1/SigningService.js';
import { SignaturePredicate } from '../../src/predicate/builtin/SignaturePredicate.js';
import { PredicateVerifierService } from '../../src/predicate/verification/PredicateVerifierService.js';
import { StateTransitionClient } from '../../src/StateTransitionClient.js';
import { TokenSalt } from '../../src/transaction/TokenSalt.js';
import { TokenType } from '../../src/transaction/TokenType.js';
import { MintJustificationVerifierService } from '../../src/transaction/verification/MintJustificationVerifierService.js';
import { TokenIssuanceVerifierService } from '../../src/transaction/verification/TokenIssuanceVerifierService.js';
import { VerificationContext } from '../../src/transaction/verification/VerificationContext.js';
import { HexConverter } from '../../src/util/HexConverter.js';
import { VerificationStatus } from '../../src/verification/VerificationStatus.js';
import { mintToken, transferToken } from '../utils/TokenUtils.js';
import { createUnicityCertificateVerifier } from '../utils/UnicityCertificateVerifierFixture.js';

/** Deterministic keys so the vector is reproducible apart from the wall-clock deadline. */
function key(n: number): Uint8Array {
  const bytes = new Uint8Array(32);
  bytes[31] = n;
  return bytes;
}

const OUT = process.env.RUST_VECTOR_OUT;

describe('Generate Rust cross-SDK vector', () => {
  it('mints and transfers Alice -> Bob -> Carol, then writes the vector', async () => {
    const aggregator = TestAggregatorClient.create(key(9));
    const client = new StateTransitionClient(aggregator);
    const trustBase = aggregator.rootTrustBase;

    const verificationContext = new VerificationContext(
      trustBase,
      PredicateVerifierService.create(),
      createUnicityCertificateVerifier(),
      new MintJustificationVerifierService(),
      new TokenIssuanceVerifierService(false),
    );

    const alice = new SigningService(key(1));
    const bob = new SigningService(key(2));
    const carol = new SigningService(key(3));
    const dave = new SigningService(key(4));

    const tokenType = new TokenType(new Uint8Array(32));
    const saltBytes = (n: number): Uint8Array => {
      const bytes = new Uint8Array(32);
      bytes[31] = n;
      return bytes;
    };

    // The Alice/Bob/Carol flow leaves the deadline to the service.
    const aliceToken = await mintToken(
      client,
      verificationContext,
      SignaturePredicate.create(alice.publicKey),
      null,
      trustBase.networkId,
      tokenType,
      TokenSalt.fromBytes(saltBytes(0)),
      null,
      null,
    );
    const bobToken = await transferToken(
      client,
      verificationContext,
      aliceToken.toCBOR(),
      SignaturePredicate.create(bob.publicKey),
      alice,
      null,
    );
    const carolToken = await transferToken(
      client,
      verificationContext,
      bobToken.toCBOR(),
      SignaturePredicate.create(carol.publicKey),
      bob,
      null,
    );

    // A second token carries a sender-chosen deadline in the same wire slot.
    const explicitTimeout = BigInt(Math.floor(Date.now() / 1000)) + 3600n;
    const explicitTimeoutToken = await mintToken(
      client,
      verificationContext,
      SignaturePredicate.create(dave.publicKey),
      null,
      trustBase.networkId,
      tokenType,
      TokenSalt.fromBytes(saltBytes(1)),
      null,
      explicitTimeout,
    );

    for (const token of [aliceToken, bobToken, carolToken, explicitTimeoutToken]) {
      await expect(token.verify(verificationContext).then((r) => r.status)).resolves.toEqual(VerificationStatus.OK);
    }

    expect(carolToken.genesis.expiresAt).toBeNull();
    expect(explicitTimeoutToken.genesis.expiresAt).toEqual(explicitTimeout);

    const vector = {
      __comment: 'generated by state-transition-sdk-js: mint to Alice, transfer Alice -> Bob -> Carol',
      trustBase: {
        networkId: NetworkId.LOCAL.id,
        nodeId: 'NODE',
        aggregatorPublicKey: HexConverter.encode(new SigningService(key(9)).publicKey),
        quorumThreshold: 1,
      },
      aliceToken: HexConverter.encode(aliceToken.toCBOR()),
      bobToken: HexConverter.encode(bobToken.toCBOR()),
      carolToken: HexConverter.encode(carolToken.toCBOR()),
      explicitTimeout: Number(explicitTimeout),
      explicitTimeoutToken: HexConverter.encode(explicitTimeoutToken.toCBOR()),
    };

    if (OUT) {
      writeFileSync(OUT, `${JSON.stringify(vector, null, 2)}\n`);
    }
  }, 120000);
});
